### ISSUE TITLE
Exception: Multiple plugins found

### ISSUE THREAD

**Issue by DanielMarchand** [aiidateam/aiida-quantumespresso#115]
Hi everyone, I'm trying to run the following basic command: 

`$launch_calculation_pw -c pw6.2.1_personal@danielLocal -p SSSP_accuracy -s 87`

But I'm getting the following exception: 

```
Traceback (most recent call last):
  File "/home/daniel/anaconda2/envs/aiida/bin/launch_calculation_pw", line 11, in <module>
    load_entry_point('aiida-quantumespresso', 'console_scripts', 'launch_calculation_pw')()
  File "/home/daniel/anaconda2/envs/aiida/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/daniel/anaconda2/envs/aiida/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/daniel/anaconda2/envs/aiida/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/daniel/anaconda2/envs/aiida/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/daniel/RnD/aiida-quantumespresso/aiida_quantumespresso/cli/calculations/pw/base.py", line 29, in launch
    PwCalculation = CalculationFactory('quantumespresso.pw')
  File "/home/daniel/anaconda2/envs/aiida/lib/python2.7/site-packages/aiida/orm/utils.py", line 34, in CalculationFactory
    suffix="Calculation")
  File "/home/daniel/anaconda2/envs/aiida/lib/python2.7/site-packages/aiida/common/pluginloader.py", line 236, in BaseFactory
    return get_plugin(category, module)
  File "/home/daniel/anaconda2/envs/aiida/lib/python2.7/site-packages/aiida/common/pluginloader.py", line 115, in get_plugin
    "Multiple plugins found for '{}' in '{}'".format(name, category))
aiida.common.exceptions.MissingPluginError: Multiple plugins found for 'quantumespresso.pw' in 'calculations'
```

Any recommendations? - Daniel

**Comment by sphuber** [comment]
Run `reentry scan` and try again. If you have installed a plugin, its entry points are registered. If you install it again, its entry points are registered again. There are now duplicate references and the plugin system does not know which one you mean. Running `reentry scan` will refresh the plugin cache

**Comment by DanielMarchand** [comment]
Thanks that worked!
