### ISSUE TITLE
A problem when adding a link to a pwimmigrant calculation.

### ISSUE THREAD

**Issue by quanshengwu** [aiidateam/aiida-quantumespresso#198]
I want to add a link to a pwimmigrant calculation like:

```
    indices= {
            'index': '(0;000)'
    }
    index_node = ParameterData(dict=indices)
    index_node.add_link_from(calc_bands, 'a_index', link_type=LinkType.CREATE)
    index_node.store()
```

But it seems that it's forbidden. 

```
Traceback (most recent call last):
  File "topo-immigrant-1.0.0a2.py", line 75, in <module>
    index_node.add_link_from(calc_bands, 'a_index', link_type=LinkType.CREATE)
  File "/Users/user/aiidapy-new/lib/python2.7/site-packages/aiida/orm/data/__init__.py", line 158, in add_link_from
    return super(Data, self).add_link_from(src, label, link_type)
  File "/Users/user/aiidapy-new/lib/python2.7/site-packages/aiida/orm/implementation/general/node.py", line 603, in add_link_from
    src._linking_as_output(self, link_type)
  File "/Users/user/aiidapy-new/lib/python2.7/site-packages/aiida/orm/implementation/general/calculation/job/__init__.py", line 241, in _linking_as_output
    valid_states, self.get_state()))
aiida.common.exceptions.ModificationNotAllowed: Can add an output node to a calculation only if it is in one of the following states: [u'SUBMITTING', u'RETRIEVING', u'PARSING'], it is instead COMPUTED

```

Is it possible to enable this linking for a immigration calculation?

**Comment by sphuber** [comment]
With the old `PwImmigrant` this is not possible because essentially you are adding an additional node that the "actual" calculation would have never attached. If you want to add the "index" as metadata, you can use the extras mechanism, e.g.:
```
calculation.set_extra('index', '(0;000)')
```
Extras can be set even after the calculation is already stored/imported so this will work and it is exactly what extras are designed for. I am closing this, if I misunderstood, feel free to explain and reopen. Moreover, we are working on a new improved immigration process that will change a lot
