### ISSUE TITLE
No module named utils.decorators

### ISSUE THREAD

**Issue by nathanielng** [aiidateam/aiida-quantumespresso#265]
I get this issue when I run the following:

```bash
$ verdi data upf listfamilies
Traceback (most recent call last):
  File "/home/m/aiida/aiida_env/bin/verdi", line 10, in <module>
    sys.exit(run())
  File "/home/m/aiida/aiida_env/local/lib/python2.7/site-packages/aiida/cmdline/verdilib.py", line 1050, in run
    aiida.cmdline.verdilib.exec_from_cmdline(sys.argv)
  File "/home/m/aiida/aiida_env/local/lib/python2.7/site-packages/aiida/cmdline/verdilib.py", line 1034, in exec_from_cmdline
    CommandClass = list_commands[command]()
  File "/home/m/aiida/aiida_env/local/lib/python2.7/site-packages/aiida/cmdline/commands/data.py", line 51, in __init__
    cmd = get_plugin('cmdline.data', ep)
  File "/home/m/aiida/aiida_env/local/lib/python2.7/site-packages/aiida/common/pluginloader.py", line 124, in get_plugin
    .format(name, traceback.format_exc()))
aiida.common.exceptions.LoadingPluginFailed: Loading the plugin 'diff' failed:
Traceback (most recent call last):
  File "/home/m/aiida/aiida_env/local/lib/python2.7/site-packages/aiida/common/pluginloader.py", line 120, in get_plugin
    plugin = entrypoint.load()
  File "/home/m/aiida/aiida_env/local/lib/python2.7/site-packages/reentry/entrypoint.py", line 38, in load
    module = import_module(self.module_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/m/aiida/aiida-diff/aiida_diff/cli.py", line 12, in <module>
    from aiida.cmdline.utils.decorators import load_dbenv_if_not_loaded
ImportError: No module named utils.decorators
```

I am able to `import aiida` but not `aiida.cmdline.utils.decorators`:

```bash
$ python
Python 2.7.13 (default, Sep 26 2018, 18:42:22) 
[GCC 6.3.0 20170516] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import aiida
>>> from aiida.cmdline.utils.decorators import load_dbenv_if_not_loaded
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named utils.decorators
>>> aiida.__version__
'0.12.3'
```

**Comment by sphuber** [comment]
This is rather a problem with the `aiida_diff` plugin. The version of it that is installed is probably not compatible with `aiida-core==0.12.3`. To fix it, you should either uninstall it, `pip uninstall aiida-diff` or install the version of it that is compatible with `aiida-core==0.12.3`. After you have done either action, run `reentry scan` to make the changes in the entry points visibile

**Comment by nathanielng** [comment]
Thanks, it works fine now. I used a fresh install that didn't have `aiida_diff`.
