### ISSUE TITLE
PP parser error

### ISSUE THREAD

**Issue by yakutovicha** [aiidateam/aiida-quantumespresso#531]
The following `pp.x` input was generated with the latest version of the `pp` plugin:

```
&INPUTPP
  filplot = 'aiida.filplot'
  outdir = './out/'
  plot_num = 11
  prefix = 'aiida'
/
&PLOT
  e1(1) =   1.0000000000d+00
  e1(2) =   0.0000000000d+00
  e1(3) =   0.0000000000d+00
  e2(1) =   0.0000000000d+00
  e2(2) =   8.9966759666d+00
  e2(3) =   0.0000000000d+00
  fileout = 'aiida.fileout'
  iflag = 2
  nx = 10
  ny = 10
  output_format = 7
  x0(1) =   0.0000000000d+00
  x0(2) =   0.0000000000d+00
  x0(3) =   6.0907239201d+00
/
```

However, the parser was not able to parse the content of the outputted [aiida.fileout](https://github.com/aiidateam/aiida-quantumespresso/files/4824870/aiida.fileout.log) file: 

```python
+-> REPORT at 2020-06-22 21:03:24.700051+00:00
 | [9385|PpCalculation|on_except]: Traceback (most recent call last):
 |   File "/opt/conda/lib/python3.7/site-packages/plumpy/process_states.py", line 220, in execute
 |     result = self.run_fn(*self.args, **self.kwargs)
 |   File "/opt/conda/lib/python3.7/site-packages/aiida/engine/processes/calcjobs/calcjob.py", line 262, in parse
 |     exit_code = execmanager.parse_results(self, retrieved_temporary_folder)
 |   File "/opt/conda/lib/python3.7/site-packages/aiida/engine/daemon/execmanager.py", line 439, in parse_results
 |     exit_code = parser.parse(**parse_kwargs)
 |   File "/opt/conda/lib/python3.7/site-packages/aiida_quantumespresso/parsers/pp.py", line 121, in parse
 |     parsed_data = self.parse_gnuplot2D(data_raw)
 |   File "/opt/conda/lib/python3.7/site-packages/aiida_quantumespresso/parsers/pp.py", line 289, in parse_gnuplot2D
 |     coords.append([float(split_line[0]), float(split_line[1])])
 | IndexError: list index out of range
```

**Comment by sphuber** [comment]
I just tried to run a `pp.x` with the following parameters (reverse engineering more or less from the input file you reported):
```
{
    'INPUTPP': {
        'plot_num': 11,
    },
    'PLOT' : {
        'iflag': 2,
        'e1': [0.1, 0, 0],
        'e2': [0, 9, 0],
        'nx': 10,
        'ny': 10,
        'x0': [0, 0, 6]
    }
}
```
but for me it parsed just fine.
Can you attach the output file that fails?

**Comment by yakutovicha** [comment]
> Can you attach the output file that fails?

I did, it is attached here:
> However, the parser was not able to parse the content of the outputted [aiida.fileout](https://github.com/aiidateam/aiida-quantumespresso/files/4824870/aiida.fileout.log) file:

**Comment by sphuber** [comment]
> > Can you attach the output file that fails?
> 
> I did, it is attached here:

Ah damn :facepalm: sorry I missed the link
