### ISSUE TITLE
bandstructure workflow code validation error

### ISSUE THREAD

**Issue by m-a-saleh** [aiidateam/aiida-quantumespresso#718]
I have the following simple bandstructure workflow as described here:
[https://aiida-tutorials.readthedocs.io/en/latest/pages/2019_Xiamen/sections/first_taste.html#from-calculations-to-workflows](url)

```
from aiida import load_profile
from aiida.orm import Code
from aiida.plugins import WorkflowFactory
from aiida.engine import submit
from aiida.orm.utils import load_node

PwBandStructureWorkChain = WorkflowFactory('quantumespresso.pw.bands')

#load the profile
load_profile()

#select the code
mycode = Code.get(label='qe-pw-6.7', machinename='localhost')

#structure
mystructure = load_node(698) #Si from http://crystallography.net/cod/9008565.cif

#submit
results = submit(
    PwBandStructureWorkChain,
    code=mycode,
    structure=mystructure,
```

It gives the following error:

```
Traceback (most recent call last):
  File "/home/saleh/Desktop/aiida-test/pw-test-workflow-bandstructure.py", line 27, in <module>
    results = submit(
  File "/home/saleh/.venvs/aiida/lib/python3.8/site-packages/aiida/engine/launch.py", line 101, in submit
    process_inited = instantiate_process(runner, process, **inputs)
  File "/home/saleh/.venvs/aiida/lib/python3.8/site-packages/aiida/engine/utils.py", line 65, in instantiate_process
    process = process_class(runner=runner, inputs=inputs)
  File "/home/saleh/.venvs/aiida/lib/python3.8/site-packages/plumpy/base/state_machine.py", line 193, in __call__
    inst.transition_to(inst.create_initial_state())
  File "/home/saleh/.venvs/aiida/lib/python3.8/site-packages/plumpy/base/state_machine.py", line 335, in transition_to
    self.transition_failed(initial_state_label, label, *sys.exc_info()[1:])
  File "/home/saleh/.venvs/aiida/lib/python3.8/site-packages/plumpy/base/state_machine.py", line 351, in transition_failed
    raise exception.with_traceback(trace)
  File "/home/saleh/.venvs/aiida/lib/python3.8/site-packages/plumpy/base/state_machine.py", line 320, in transition_to
    self._enter_next_state(new_state)
  File "/home/saleh/.venvs/aiida/lib/python3.8/site-packages/plumpy/base/state_machine.py", line 382, in _enter_next_state
    self._fire_state_event(StateEventHook.ENTERING_STATE, next_state)
  File "/home/saleh/.venvs/aiida/lib/python3.8/site-packages/plumpy/base/state_machine.py", line 299, in _fire_state_event
    callback(self, hook, state)
  File "/home/saleh/.venvs/aiida/lib/python3.8/site-packages/plumpy/processes.py", line 324, in <lambda>
    lambda _s, _h, state: self.on_entering(cast(process_states.State, state)),
  File "/home/saleh/.venvs/aiida/lib/python3.8/site-packages/aiida/engine/processes/process.py", line 380, in on_entering
    super().on_entering(state)
  File "/home/saleh/.venvs/aiida/lib/python3.8/site-packages/plumpy/processes.py", line 669, in on_entering
    call_with_super_check(self.on_create)
  File "/home/saleh/.venvs/aiida/lib/python3.8/site-packages/plumpy/base/utils.py", line 29, in call_with_super_check
    wrapped(*args, **kwargs)
  File "/home/saleh/.venvs/aiida/lib/python3.8/site-packages/aiida/engine/processes/process.py", line 370, in on_create
    super().on_create()
  File "/home/saleh/.venvs/aiida/lib/python3.8/site-packages/plumpy/base/utils.py", line 16, in wrapper
    wrapped(self, *args, **kwargs)
  File "/home/saleh/.venvs/aiida/lib/python3.8/site-packages/plumpy/processes.py", line 726, in on_create
    raise ValueError(result)
ValueError: Error occurred validating port 'inputs.scf.pw.code': required value was not provided for 'code'
```

The selected code is working normally for non-workchain jobs

**Comment by m-a-saleh** [comment]
Sorry. Found the updated version here:
https://aiida-tutorials.readthedocs.io/en/tutorial-2021-intro/sections/running_processes/workflows.html
