### ISSUE TITLE
`PwParser`: Parsing of magnetic moments fails for QE v6.8

### ISSUE THREAD

**Issue by mbercx** [aiidateam/aiida-quantumespresso#726]
After doing a test run with QE v6.8 on eiger with spin-polarisation, it seems that the parsing of the magnetic moments fails:

```
+-> CRITICAL at 2021-09-10 11:54:54.744964+00:00
 | Traceback (most recent call last):
 |   File "/home/aiida/envs/aiida-lumi/code/aiida-quantumespresso/aiida_quantumespresso/parsers/pw.py", line 324, in parse_stdout
 |     parsed_data, logs = parse_stdout(stdout, parameters, parser_options, parsed_xml)
 |   File "/home/aiida/envs/aiida-lumi/code/aiida-quantumespresso/aiida_quantumespresso/parsers/parse_raw/pw.py", line 640, in parse_stdout
 |     line2 = data_step[count + j]
 | IndexError: list index out of range
+-> ERROR at 2021-09-10 11:54:54.747584+00:00
 | The parser raised an unexpected exception.
+-> WARNING at 2021-09-10 11:54:54.749605+00:00
 | output parser returned exit code<350>: The parser raised an unexpected exception.
```

Closer inspection reveals that this is most likely due to a change in format of the corresponding output. This is the format for the magnetic moments in v6.8:

```
     Magnetic moment per site  (integrated on atomic sphere of radius R)
     atom   1 (R=0.292)  charge=  7.9920  magn= -0.0000
     atom   2 (R=0.292)  charge=  1.2243  magn=  0.0000
```

Compare that to the following example from v6.7:

```
     Magnetic moment per site:
     atom:    1    charge:    0.4485    magn:    0.0000    constr:    0.0000
     atom:    2    charge:    0.4485    magn:    0.0000    constr:    0.0000
     atom:    3    charge:    4.1095    magn:   -0.0000    constr:    0.0000
     atom:    4    charge:    4.1095    magn:   -0.0000    constr:    0.0000
```

This messes up the current parsing:

https://github.com/aiidateam/aiida-quantumespresso/blob/c49def7a238617439feb75afd0d0cf9fbb681613/aiida_quantumespresso/parsers/parse_raw/pw.py#L641-L643

**Comment by mbercx** [comment]
@pietrodelugas just to be sure: the magnetic moments per site are not yet in the XML, correct? If so, would it be possible to add these in the future so we can make our parsing more robust? 😇 🙏

**Comment by pietrodelugas** [comment]
yes @mbercx they are not in the schema. And it is definitely the case to include them.
