### ISSUE TITLE
`PwParser`: Stress parsing is broken for native QE GPU version

### ISSUE THREAD

**Issue by mbercx** [aiidateam/aiida-quantumespresso#775]
When running a simple `PwCalculation` with the native GPU Quantum ESPRESSO code (more specifically, with the `QuantumESPRESSO/6.6a2-CrayPGI-20.11-cuda` module on daint), the parsing of the stress tensor fails:

```
*** 1 LOG MESSAGES:
+-> WARNING at 2022-01-28 13:10:51.975859+00:00
 | Error while parsing stress tensor: "P=" not found within 15 lines from the start of the stress block
```

Looking at the `stdout`, it's clear to see why:

```
     Computing stress (Cartesian axis) and pressure

 Really copied psic H->D
 Really copied psic D->H
 Really copied psic H->D
 Really copied psic D->H
 Really copied psic H->D
 Really copied psic D->H
 Really copied evc H->D
 Really copied evc H->D
 Really copied evc H->D
 Really copied evc H->D
 Really copied evc H->D
 Really copied evc H->D
 Really copied evc H->D
 Really copied evc H->D
 Really copied evc H->D
 Really copied evc H->D
 Really copied evc H->D
 Really copied evc H->D
 Really copied evc H->D
          total   stress  (Ry/bohr**3)                   (kbar)     P=        5.92
   0.00004025   0.00000000   0.00000000            5.92        0.00        0.00
   0.00000000   0.00004025  -0.00000000            0.00        5.92       -0.00
   0.00000000  -0.00000000   0.00004024            0.00       -0.00        5.92
```

In fact, the `stdout` is flooded with these `Really copied` lines, making the output file unnecessarily large, and potentially breaking other `stdout` parsing code as well.

@pietrodelugas is this output related to a badly configured compilation setting, or is it always present in the GPU version of QE?

EDIT: Thanks to @tsthakur for reporting! 😄

**Comment by mbercx** [comment]
Note that this causes a `vc-relax` `PwCalculation` to `Except`:

```
*** 2 LOG MESSAGES:
+-> REPORT at 2022-01-28 13:35:15.540322+00:00
 | [6569|PwCalculation|on_except]: Traceback (most recent call last):
 |   File "/home/mbercx/envs/aiida-dev/code/aiida-quantumespresso/aiida_quantumespresso/utils/validation/trajectory.py", line 84, in verify_convergence_stress
 |     stress = trajectory.get_array('stress')[index]
 |   File "/home/mbercx/.virtualenvs/aiida-dev/lib/python3.8/site-packages/aiida/orm/nodes/data/array/array.py", line 122, in get_array
 |     return get_array_from_file(self, name)
 |   File "/home/mbercx/.virtualenvs/aiida-dev/lib/python3.8/site-packages/aiida/orm/nodes/data/array/array.py", line 114, in get_array_from_file
 |     raise KeyError(f'Array with name `{name}` not found in ArrayData<{self.pk}>')
 | KeyError: 'Array with name `stress` not found in ArrayData<None>'
 | 
 | The above exception was the direct cause of the following exception:
 | 
 | Traceback (most recent call last):
 |   File "/home/mbercx/.virtualenvs/aiida-dev/lib/python3.8/site-packages/plumpy/process_states.py", line 231, in execute
 |     result = self.run_fn(*self.args, **self.kwargs)
 |   File "/home/mbercx/.virtualenvs/aiida-dev/lib/python3.8/site-packages/aiida/engine/processes/calcjobs/calcjob.py", line 388, in parse
 |     exit_code_retrieved = self.parse_retrieved_output(retrieved_temporary_folder)
 |   File "/home/mbercx/.virtualenvs/aiida-dev/lib/python3.8/site-packages/aiida/engine/processes/calcjobs/calcjob.py", line 468, in parse_retrieved_output
 |     exit_code = parser.parse(**parse_kwargs)
 |   File "/home/mbercx/envs/aiida-dev/code/aiida-quantumespresso/aiida_quantumespresso/parsers/pw.py", line 123, in parse
 |     exit_code = validator(trajectory, parsed_parameters, logs_stdout)
 |   File "/home/mbercx/envs/aiida-dev/code/aiida-quantumespresso/aiida_quantumespresso/parsers/pw.py", line 201, in validate_ionic
 |     if not self.is_ionically_converged(trajectory):
 |   File "/home/mbercx/envs/aiida-dev/code/aiida-quantumespresso/aiida_quantumespresso/parsers/pw.py", line 244, in is_ionically_converged
 |     converged_relax = verify_convergence_trajectory(trajectory, -2, *values)
 |   File "/home/mbercx/envs/aiida-dev/code/aiida-quantumespresso/aiida_quantumespresso/utils/validation/trajectory.py", line 33, in verify_convergence_trajectory
 |     converged_stress = verify_convergence_stress(trajectory, index, threshold_stress, reference_pressure)
 |   File "/home/mbercx/envs/aiida-dev/code/aiida-quantumespresso/aiida_quantumespresso/utils/validation/trajectory.py", line 86, in verify_convergence_stress
 |     raise ValueError('the `stress` array does not exist or the given index exceeds the length.') from exception
 | ValueError: the `stress` array does not exist or the given index exceeds the length.
+-> WARNING at 2022-01-28 13:35:15.480941+00:00
 | Error while parsing stress tensor: "P=" not found within 15 lines from the start of the stress block
```

**Comment by pietrodelugas** [comment]
No bad compilation.   verbosity is set to 'high' in &control and it prints out a message every time data are copied to the GPU. 
we should move this stuff only in the debug compilation.  6.6 was somewhat experimental; 7.0 is not anymore but those messages are still there. 
thanks for tagging me.

**Comment by mbercx** [comment]
Thanks for the reply, @pietrodelugas! We'll have to adapt the parser a bit based on the verbosity level. Or maybe simply filter these lines out before parsing starts.
