### ISSUE TITLE
PW parser ignores XML information on trajectories?

### ISSUE THREAD

**Issue by ltalirz** [aiidateam/aiida-quantumespresso#796]
While running the new sirius-enabled QE, I came across the following exception

```
+-> REPORT at 2022-03-21 16:56:05.830566+00:00
 | [6447|PwCalculation|on_except]: Traceback (most recent call last):
 |   File "/nfshome/a-ctalirz/software/aiida-quantumespresso/aiida_quantumespresso/utils/validation/trajectory.py", line 57, in verify_convergence_forces
 |     forces = trajectory.get_array('forces')[index]
 |   File "/nfshome/a-ctalirz/software/aiida-core/aiida/orm/nodes/data/array/array.py", line 122, in get_array
 |     return get_array_from_file(self, name)
 |   File "/nfshome/a-ctalirz/software/aiida-core/aiida/orm/nodes/data/array/array.py", line 114, in get_array_from_file
 |     raise KeyError(f'Array with name `{name}` not found in ArrayData<{self.pk}>')
 | KeyError: 'Array with name `forces` not found in ArrayData<None>'
```

Next, I looked inside the XML file and found information like

```xml
<step>
    <scf_conv>
      <convergence_achieved>true</convergence_achieved>
      <n_scf_steps>28</n_scf_steps>
      <scf_error>0.000000000000000e0</scf_error>
    </scf_conv>
    <atomic_structure nat="13" alat="9.895594598859e0">
      <atomic_positions>
        <atom name="Rb" index="1">1.784361828281981e0 1.525504289831838e0 2.099727653663269e0</atom>
        <atom name="Rb" index="2">2.062259419776172e0 7.436429585950569e0 2.580386203405535e0</atom>
        <atom name="Li" index="3">7.024602975168970e0 4.414118920333656e0 1.241958088138374e1</atom>
        <atom name="Mg" index="4">6.953402997699220e0 4.372309698303431e0 6.272734011157548e0</atom>
        <atom name="Sc" index="5">1.830567033323358e0 7.290777426144463e0 9.110218529689392e0</atom>
        <atom name="V" index="6">1.798491163920761e0 1.229432054136752e0 8.640506084774371e0</atom>
        <atom name="O" index="7">3.936707766331974e-1 4.337798532008406e0 6.911730005861294e0</atom>
        <atom name="O" index="8">4.957317384642713e0 1.284953392548574e0 6.784648128568714e0</atom>
        <atom name="O" index="9">5.321989575405887e0 7.593863209426486e0 7.214476137448994e0</atom>
        <atom name="O" index="10">-1.416370111482030e0 7.599987587018401e0 1.135547811451637e1</atom>
        <atom name="F" index="11">3.424616600762097e0 4.275144731099309e0 1.137161990767617e1</atom>
        <atom name="F" index="12">7.014888218091576e0 4.318613892052463e0 2.522849216697887e0</atom>
        <atom name="F" index="13">8.567406185617154e0 1.118672090739684e0 1.129702851706784e1</atom>
      </atomic_positions>
      <cell>
        <a1>1.016590632787812e1 -8.556579732860246e-2 4.000805369434143e-1</a1>
        <a2>-4.740042762423892e0 9.006233661591356e0 4.628632781781575e-1</a2>
        <a3>-1.492732222786088e-1 -1.823623866049239e-1 1.342912058163692e1</a3>
      </cell>
    </atomic_structure>
    <total_energy>
      <etot>-3.484259701295239e2</etot>
      <eband>-2.662346146115513e1</eband>
      <ehart>1.018010769955228e2</ehart>
      <vtxc>-6.868955155728847e1</vtxc>
      <etxc>-5.505038364033203e1</etxc>
      <ewald>-1.995385752363808e2</ewald>
      <demet>-1.595899701647708e-3</demet>
    </total_energy>
    <forces rank="2" dims="3 13">
      -3.910611191340307e-4 -5.607856965009798e-4 -1.215394205603736e-3
      7.802019753183654e-4 7.798003368737444e-4 -2.100268096757895e-3
      1.682809575330447e-4 2.299517433236749e-3 -6.357649667651676e-3
      1.840232864505252e-3 1.004308623856108e-3 1.026221395597608e-2
      -6.921105500984720e-3 -2.843167553635732e-3 -2.871320845850788e-3
      1.635264361971759e-3 -1.101831200526892e-2 -1.596008113229272e-3
      1.681007765482685e-3 -3.677725262604277e-4 9.384346288729173e-4
      -8.463713962804984e-4 -2.693860619366919e-3 -3.606257056384969e-3
      2.044132081892101e-3 5.702266856839660e-3 2.110965167460739e-3
      -6.582670529565558e-5 1.078901315440902e-2 -6.337606814110083e-3
      1.636045453117968e-4 -1.539533313771467e-3 3.721053707151423e-3
      2.071866915401946e-4 -4.015126622757586e-4 4.524751937604099e-3
      -2.955465218602955e-4 -1.149962028135086e-3 2.527085402523166e-3
      </forces>
  </step>
```

I.e. information on the forces was present.

I then tried to understand the codepath followed by the parser and came across this line:
https://github.com/aiidateam/aiida-quantumespresso/blob/0c8a6114dfb740262fd408c7b0fc73bd0fde33ee/aiida_quantumespresso/parsers/parse_raw/pw.py#L306

Does this mean the PW parser ignores the information on trajectories that is present in the XML file?

It is quite possible that the log parser is broken for sirius-enabled QE, so it would seem to make sense to read this information from the XML if possible.

**Comment by mbercx** [comment]
Hi @ltalirz. Yes, the forces are currently still parsed from the `stdout`. Seems like a good time to switch to parsing them from the XML indeed. The current parsing is done here:

https://github.com/aiidateam/aiida-quantumespresso/blob/0c8a6114dfb740262fd408c7b0fc73bd0fde33ee/aiida_quantumespresso/parsers/parse_raw/pw.py#L763-L780

The XML parsing is done here:

https://github.com/aiidateam/aiida-quantumespresso/blob/develop/aiida_quantumespresso/parsers/parse_xml/parse.py

You'd also have to change some logic in the `PwParser`, to get the `trajectory` from the parsed XML instead of the stdout:

https://github.com/aiidateam/aiida-quantumespresso/blob/0c8a6114dfb740262fd408c7b0fc73bd0fde33ee/aiida_quantumespresso/parsers/pw.py#L45-L52

Great if you want to provide a fix, else I'll try to get to it asap. I'm at a conference the next few days though.
