### ISSUE TITLE
Error during conversion of walltime during parsing of `pw.x` calculation

### ISSUE THREAD

**Issue by mbercx** [aiidateam/aiida-quantumespresso#797]
Reported by @Ezio-droid in https://github.com/aiidateam/aiida-core/discussions/5452

---

Hi all,

I am following the tutorial given [on following link](https://aiida-tutorials.readthedocs.io/en/tutorial-qe-short/source/sections/qe.html#importing-a-structure-and-inspecting-it). And while I was seeing the process report for the job I got following errors. Can someone suggest the reason for these errors?

```console
verdi process report 116
*** 116: None
*** (empty scheduler output file)
*** (empty scheduler errors file)
*** 3 LOG MESSAGES:
+-> CRITICAL at 2022-03-16 00:32:15.000564+00:00
| Traceback (most recent call last):
| File "/home/tanay/miniconda3/envs/aiida/lib/python3.9/site-packages/aiida_quantumespresso/parsers/parse_raw/pw.py", line 434, in parse_stdout
| parsed_data['wall_time_seconds'] = convert_qe_time_to_sec(time)
| File "/home/tanay/miniconda3/envs/aiida/lib/python3.9/site-packages/aiida_quantumespresso/parsers/parse_raw/base.py", line 137, in convert_qe_time_to_sec
| num_seconds = (float(seconds) + float(minutes) * 60. + float(hours) * 3600. + float(days) * 86400.)
| ValueError: could not convert string to float: 'PWSCF : 2.46'
|
| During handling of the above exception, another exception occurred:
|
| Traceback (most recent call last):
| File "/home/tanay/miniconda3/envs/aiida/lib/python3.9/site-packages/aiida_quantumespresso/parsers/pw.py", line 325, in parse_stdout
| parsed_data, logs = parse_stdout(stdout, parameters, parser_options, parsed_xml)
| File "/home/tanay/miniconda3/envs/aiida/lib/python3.9/site-packages/aiida_quantumespresso/parsers/parse_raw/pw.py", line 436, in parse_stdout
| raise QEOutputParsingError('Unable to convert wall_time in seconds.')
| aiida_quantumespresso.parsers.QEOutputParsingError: Unable to convert wall_time in seconds.
+-> ERROR at 2022-03-16 00:32:15.006631+00:00
| The parser raised an unexpected exception.
+-> WARNING at 2022-03-16 00:32:15.009005+00:00
| output parser returned exit code<350>: The parser raised an unexpected exception.
```

**Comment by mbercx** [comment]
Thanks for reporting @Ezio-droid! Which version of QE are you running? Could you by any chance provide the output files of your calculations so I can have a look?
